server:
  port: 9001

spring:
  application:
    name: accounts
    datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      password: ${MYSQL_DATABASE_PASSWORD:matome$123}
      url: jdbc:mysql://localhost:3306/accounts?useSSL=true&autoReconnect=true
      username: ${MYSQL_DATABASE_USER:accounts}

logging:
  file:
    name: ${user.home}/Documents/accounts.log